FROM node:24-slim AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

FROM base AS build
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
RUN npm run build

FROM base AS runtime

ARG GIT_SHA=""
ENV GIT_SHA=${GIT_SHA}

ARG PORT=3000
ENV PORT=${PORT}

ARG MYSQL_HOST=""
ENV MYSQL_HOST=${MYSQL_HOST}
ARG MYSQL_PORT=3306
ENV MYSQL_PORT=${MYSQL_PORT}
ARG MYSQL_USER=""
ENV MYSQL_USER=${MYSQL_USER}
ARG MYSQL_PASSWORD=""
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ARG MYSQL_DATABASE=""
ENV MYSQL_DATABASE=${MYSQL_DATABASE}

ARG MONGO_URI=""
ENV MONGO_URI=${MONGO_URI}

ARG REDIS_HOST=""
ENV REDIS_HOST=${REDIS_HOST}
ARG REDIS_PORT=6379
ENV REDIS_PORT=${REDIS_PORT}

ARG JWT_SECRET=""
ENV JWT_SECRET=${JWT_SECRET}
ARG JWT_EXPIRES_IN=1h
ENV JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

ARG CATENOID_API_BASE_URL=""
ENV CATENOID_API_BASE_URL=${CATENOID_API_BASE_URL}
ARG CATENOID_SERVICE_ACCOUNT_KEY=""
ENV CATENOID_SERVICE_ACCOUNT_KEY=${CATENOID_SERVICE_ACCOUNT_KEY}
ARG CATENOID_API_ACCESS_TOKEN=""
ENV CATENOID_API_ACCESS_TOKEN=${CATENOID_API_ACCESS_TOKEN}
ARG CATENOID_CUSTOM_KEY=""
ENV CATENOID_CUSTOM_KEY=${CATENOID_CUSTOM_KEY}
ARG CATENOID_SECURITY_KEY=""
ENV CATENOID_SECURITY_KEY=${CATENOID_SECURITY_KEY}

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY package.json ./

EXPOSE ${PORT}

CMD ["node", "dist/main"]
